import React from 'react'
import { createRoot } from 'react-dom/client'
import QRCode from 'qrcode'
import { ArrowUpRight, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Download, LayoutDashboard, Menu, MoreHorizontal, QrCode, ScanLine, Search, Settings, Users, X } from 'lucide-react'
import './styles.css'

type Guest = { name: string; code: string; type: string; time: string; state: 'Checked in' | 'Pending' }
const seed: Guest[] = [
  { name: 'Nadia Permata', code: 'RSV-0842', type: 'VIP', time: '09:42 WIB', state: 'Checked in' },
  { name: 'Raka Pratama', code: 'RSV-0839', type: 'Regular', time: '09:38 WIB', state: 'Checked in' },
  { name: 'Sinta Maheswari', code: 'RSV-0835', type: 'Family', time: '09:31 WIB', state: 'Checked in' },
  { name: 'Dimas Wicaksono', code: 'RSV-0828', type: 'Regular', time: '—', state: 'Pending' },
]
const navItems = ['Overview', 'Guests', 'QR codes', 'Check-in']

function App() {
  const [menu, setMenu] = React.useState(false)
  const [activeView, setActiveView] = React.useState('Overview')
  const [guestData, setGuestData] = React.useState<Guest[]>(() => { try { return JSON.parse(localStorage.getItem('rsvply-guests') || 'null') || seed } catch { return seed } })
  const [query, setQuery] = React.useState('')
  const [filter, setFilter] = React.useState<'All guests' | 'Checked in' | 'Pending'>('All guests')
  const [scanner, setScanner] = React.useState(false)
  const [scanCode, setScanCode] = React.useState('')
  const [scanResult, setScanResult] = React.useState<string | null>(null)
  const [qrImages, setQrImages] = React.useState<Record<string, string>>({})

  React.useEffect(() => { document.body.style.overflow = menu || scanner ? 'hidden' : ''; const close = (e: KeyboardEvent) => e.key === 'Escape' && (setMenu(false), setScanner(false)); document.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; document.removeEventListener('keydown', close) } }, [menu, scanner])
  React.useEffect(() => { if (activeView !== 'QR codes') return; guestData.forEach(g => QRCode.toDataURL(`rsvply://event/ruang-rasa?guest=${g.code}`, { width: 180, margin: 1 }).then(url => setQrImages(prev => ({ ...prev, [g.code]: url })))) }, [activeView, guestData])

  const visible = guestData.filter(g => `${g.name} ${g.code}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All guests' || g.state === filter))
  const checkIn = () => { const code = scanCode.trim().toUpperCase(); const guest = guestData.find(g => g.code === code); if (!guest) return setScanResult('Kode QR tidak ditemukan.'); if (guest.state === 'Checked in') return setScanResult(`${guest.name} sudah check-in pada ${guest.time}.`); const next = guestData.map(g => g.code === code ? { ...g, state: 'Checked in' as const, time: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) + ' WIB' } : g); setGuestData(next); localStorage.setItem('rsvply-guests', JSON.stringify(next)); setScanResult(`${guest.name} berhasil check-in.`) }
  const exportGuests = () => { const csv = ['Name,Code,Type,Time,Status', ...guestData.map(g => [g.name, g.code, g.type, g.time, g.state].join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'rsvply-guests.csv'; link.click(); URL.revokeObjectURL(link.href) }
  const downloadQr = (g: Guest) => { const link = document.createElement('a'); link.href = qrImages[g.code]; link.download = `${g.code}-${g.name.replace(/\s+/g, '-').toLowerCase()}.png`; link.click() }
  const openView = (view: string) => { setActiveView(view); setMenu(false) }
  const metrics = { checked: guestData.filter(g => g.state === 'Checked in').length, pending: guestData.filter(g => g.state === 'Pending').length }

  return <div className="app">
    {menu && <button className="drawer-backdrop" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside id="event-navigation" className={menu ? 'sidebar open' : 'sidebar'} aria-hidden={!menu}>
      <div className="brand"><span className="brand-mark">R</span><span>rsvply</span></div><div className="event-switcher"><span className="eyebrow">ACTIVE EVENT</span><b>Ruang Rasa — Launch Night</b><span className="event-date">24 SEP 2026 <ChevronDown size={14}/></span></div>
      <nav>{navItems.map((item, i) => <button className={activeView === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => openView(item)}>{[<LayoutDashboard size={17}/>, <Users size={17}/>, <QrCode size={17}/>, <ScanLine size={17}/>][i]} {item}</button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item"><Settings size={17}/> Settings</button><button className="nav-item"><CircleHelp size={17}/> Help centre</button><div className="profile"><span>FS</span><div><b>Fadjri Saputro</b><small>Event admin</small></div><MoreHorizontal size={17}/></div></div>
    </aside>
    <main><header><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation" aria-controls="event-navigation" aria-expanded={menu}><Menu size={20}/></button><div className="greeting"><span className="eyebrow">{activeView.toUpperCase()}</span><h1>Good morning, Fadjri.</h1></div><div className="header-actions"><button className="quiet" onClick={exportGuests} aria-label="Export guest data"><Download size={16}/> <span>Export</span></button><button className="primary" onClick={() => { setScanResult(null); setScanner(true) }}><ScanLine size={16}/> Open scanner</button></div></header>
      <div className="content">{activeView === 'Overview' && <Overview metrics={metrics} guestData={guestData} onScan={() => setScanner(true)} />}{activeView === 'Guests' && <GuestList guests={visible} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} />}{activeView === 'QR codes' && <QrList guests={guestData} images={qrImages} download={downloadQr} />}{activeView === 'Check-in' && <CheckInPage guests={guestData} onOpen={() => setScanner(true)} />}</div>
    </main>
    {scanner && <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><div className="scanner-modal"><button className="modal-close" onClick={() => setScanner(false)} aria-label="Close scanner"><X size={18}/></button><span className="eyebrow">CHECK-IN</span><h2 id="scanner-title">Scan guest QR</h2><p className="muted">Masukkan kode QR tamu. Kamera fisik bisa disambungkan ke backend berikutnya.</p><label className="scan-input"><span className="eyebrow">GUEST CODE</span><input autoFocus value={scanCode} onChange={e => { setScanCode(e.target.value); setScanResult(null) }} onKeyDown={e => e.key === 'Enter' && checkIn()} placeholder="Contoh: RSV-0828" /></label><button className="primary scanner-close" onClick={checkIn}>Check-in guest</button>{scanResult && <p className={scanResult.includes('berhasil') ? 'scan-success' : 'scan-error'}>{scanResult}</p>}<button className="quiet scanner-close" onClick={() => setScanner(false)}>Close scanner</button></div></div>}
  </div>
}

function Overview({ metrics, guestData, onScan }: { metrics: { checked: number; pending: number }; guestData: Guest[]; onScan: () => void }) { const latest = guestData.find(g => g.state === 'Checked in'); return <><section className="intro"><div><p className="kicker">LIVE EVENT / DOORS OPEN</p><h2>Ruang Rasa<br/><em>Launch Night</em></h2><p className="muted">A quick read on tonight's arrivals. Last sync 2 minutes ago.</p></div><div className="intro-meta"><span><CalendarDays size={16}/> 24 September 2026</span><span><Clock3 size={16}/> 18:00 — 22:00 WIB</span></div></section><section className="metrics"><Metric label="Checked in" value={String(metrics.checked)} detail="of guest list" tone="olive"/><Metric label="Still expected" value={String(metrics.pending)} detail="waiting to arrive"/><Metric label="QR scans" value="341" detail="13 repeat scans"/><Metric label="Latest arrival" value={latest?.time || '—'} detail={latest?.name || 'No arrival'} tone="brown"/></section><GuestList guests={guestData} query="" setQuery={() => {}} filter="All guests" setFilter={() => {}} compact onScan={onScan} /></> }
function Metric({ label, value, detail, tone = '' }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><span>{detail}</span></article> }
function GuestList({ guests, query, setQuery, filter, setFilter, compact = false, onScan }: { guests: Guest[]; query: string; setQuery: (v: string) => void; filter: 'All guests' | 'Checked in' | 'Pending'; setFilter: (v: 'All guests' | 'Checked in' | 'Pending') => void; compact?: boolean; onScan?: () => void }) { return <section className="panel arrivals"><div className="panel-head"><div><span className="eyebrow">GUESTS</span><h3>{compact ? 'Recent check-ins' : 'Guest list'}</h3></div>{onScan && <button className="text-button" onClick={onScan}>Scan guest <ScanLine size={15}/></button>}</div><div className="table-tools"><label><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search guests or code" /></label><select className="filter" value={filter} onChange={e => setFilter(e.target.value as typeof filter)} aria-label="Filter guests"><option>All guests</option><option>Checked in</option><option>Pending</option></select></div><div className="table"><div className="table-row table-label"><span>GUEST</span><span>TYPE</span><span>TIME</span><span>STATUS</span></div>{guests.map(g => <div className="table-row" key={g.code}><div className="guest"><span className="avatar">{g.name.split(' ').map(x => x[0]).join('')}</span><div><b>{g.name}</b><small>{g.code}</small></div></div><span className="type">{g.type}</span><span className="time">{g.time}</span><span className={`status ${g.state === 'Checked in' ? 'done' : 'pending'}`}>{g.state === 'Checked in' && <Check size={13}/>} {g.state}</span></div>)}</div></section> }
function QrList({ guests, images, download }: { guests: Guest[]; images: Record<string, string>; download: (g: Guest) => void }) { return <section className="panel arrivals"><div className="panel-head"><div><span className="eyebrow">QR CODES</span><h3>Guest passes</h3><p className="muted">Satu QR unik untuk satu tamu. Download lalu kirim atau print.</p></div></div><div className="qr-grid">{guests.map(g => <article className="qr-card" key={g.code}>{images[g.code] ? <img src={images[g.code]} alt={`QR ${g.name}`} /> : <div className="qr-loading">Generating</div>}<b>{g.name}</b><code>{g.code}</code><button className="text-button" onClick={() => download(g)} disabled={!images[g.code]}><Download size={14}/> Download PNG</button></article>)}</div></section> }
function CheckInPage({ guests, onOpen }: { guests: Guest[]; onOpen: () => void }) { return <section className="checkin-page"><div className="checkin-copy"><span className="eyebrow">DOOR DESK</span><h2>Ready to welcome<br/><em>your guests.</em></h2><p className="muted">Open scanner, enter the code printed on a guest pass, and the dashboard will reject repeat check-ins.</p><button className="primary" onClick={onOpen}><ScanLine size={17}/> Open scanner</button></div><div className="checkin-guide panel"><span className="eyebrow">CHECK-IN FLOW</span><div><b>01</b><span>Open scanner</span></div><div><b>02</b><span>Enter guest code</span></div><div><b>03</b><span>Confirm arrival</span></div><small>{guests.filter(g => g.state === 'Checked in').length} guests checked in so far</small></div></section> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
