import React from 'react'
import { createRoot } from 'react-dom/client'
import QRCode from 'qrcode'
import { ArrowUpRight, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Download, LayoutDashboard, Menu, MoreHorizontal, QrCode, ScanLine, Search, Settings, Users, X } from 'lucide-react'
import './styles.css'

type Guest = { name: string; code: string; type: string; time: string; state: 'Checked in' | 'Pending' }
const seed: Guest[] = [
  { name: 'Nadia Permata', code: 'RSV-0842', type: 'VIP', time: '09:42 WIB', state: 'Checked in' },
  { name: 'Raka Pratama', code: 'RSV-0839', type: 'Regular', time: '09:38 WIB', state: 'Checked in' },
  { name: 'Sinta Maheswari', code: 'RSV-0835', type: 'Family', time: '09:31 WIB', state: 'Checked in' },
  { name: 'Dimas Wicaksono', code: 'RSV-0828', type: 'Regular', time: '—', state: 'Pending' },
]
const navItems = ['Overview', 'Guests', 'QR codes', 'Check-in']
type UtilityView = 'Settings' | 'Help centre' | 'Login' | 'Add guest' | null

function App() {
  const [menu, setMenu] = React.useState(false)
  const [activeView, setActiveView] = React.useState('Overview')
  const [utilityView, setUtilityView] = React.useState<UtilityView>(null)
  const [profileMenu, setProfileMenu] = React.useState(false)
  const [loggedIn, setLoggedIn] = React.useState(() => localStorage.getItem('rsvply-session') === 'demo')
  const [loginEmail, setLoginEmail] = React.useState('')
  const [loginPassword, setLoginPassword] = React.useState('')
  const [camera, setCamera] = React.useState(false)
  const videoRef = React.useRef<HTMLVideoElement>(null)
  const cameraStream = React.useRef<MediaStream | null>(null)
  const [guestData, setGuestData] = React.useState<Guest[]>(() => { try { return JSON.parse(localStorage.getItem('rsvply-guests') || 'null') || seed } catch { return seed } })
  const [query, setQuery] = React.useState('')
  const [filter, setFilter] = React.useState<'All guests' | 'Checked in' | 'Pending'>('All guests')
  const [scanner, setScanner] = React.useState(false)
  const [scanCode, setScanCode] = React.useState('')
  const [scanResult, setScanResult] = React.useState<string | null>(null)
  const [qrImages, setQrImages] = React.useState<Record<string, string>>({})
  const [guestForm, setGuestForm] = React.useState({ name: '', type: 'Regular' })

  React.useEffect(() => { document.body.style.overflow = menu || scanner || utilityView ? 'hidden' : ''; const close = (e: KeyboardEvent) => e.key === 'Escape' && (setMenu(false), setScanner(false), setUtilityView(null)); document.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; document.removeEventListener('keydown', close) } }, [menu, scanner, utilityView])
  React.useEffect(() => { if (activeView !== 'QR codes') return; guestData.forEach(g => QRCode.toDataURL(`rsvply://event/ruang-rasa?guest=${g.code}`, { width: 180, margin: 1 }).then(url => setQrImages(prev => ({ ...prev, [g.code]: url })))) }, [activeView, guestData])
  React.useEffect(() => { if (!camera) return; let timer = 0; const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); cameraStream.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play() } const Detector = (window as Window & { BarcodeDetector?: new (options?: { formats?: string[] }) => { detect: (source: HTMLVideoElement) => Promise<Array<{ rawValue?: string }>> } }).BarcodeDetector; if (!Detector) return; const detector = new Detector({ formats: ['qr_code'] }); const scan = async () => { if (!videoRef.current || !camera) return; const codes = await detector.detect(videoRef.current).catch(() => []); const value = codes[0]?.rawValue?.match(/(?:guest=)?(RSV-\d{4})/i)?.[1]; if (value) { setScanCode(value.toUpperCase()); setCamera(false); setScanResult(null) } else timer = window.setTimeout(scan, 300) }; scan() } catch { setScanResult('Kamera tidak bisa diakses. Izinkan camera atau gunakan input kode manual.') } }; start(); return () => { window.clearTimeout(timer); cameraStream.current?.getTracks().forEach(track => track.stop()); cameraStream.current = null } }, [camera])

  const visible = guestData.filter(g => `${g.name} ${g.code}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All guests' || g.state === filter))
  const checkIn = () => { const code = scanCode.trim().toUpperCase(); const guest = guestData.find(g => g.code === code); if (!guest) return setScanResult('Kode QR tidak ditemukan.'); if (guest.state === 'Checked in') return setScanResult(`${guest.name} sudah check-in pada ${guest.time}.`); const next = guestData.map(g => g.code === code ? { ...g, state: 'Checked in' as const, time: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' }) + ' WIB' } : g); setGuestData(next); localStorage.setItem('rsvply-guests', JSON.stringify(next)); setScanResult(`${guest.name} berhasil check-in.`) }
  const exportGuests = () => { const csv = ['Name,Code,Type,Time,Status', ...guestData.map(g => [g.name, g.code, g.type, g.time, g.state].join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'rsvply-guests.csv'; link.click(); URL.revokeObjectURL(link.href) }
  const downloadQr = (g: Guest) => { const link = document.createElement('a'); link.href = qrImages[g.code]; link.download = `${g.code}-${g.name.replace(/\s+/g, '-').toLowerCase()}.png`; link.click() }
  const openView = (view: string) => { setActiveView(view); setUtilityView(null); setMenu(false) }
  const openUtility = (view: UtilityView) => { setUtilityView(view); setProfileMenu(false); setMenu(false) }
  const addGuest = () => { const name = guestForm.name.trim(); if (!name) return; const code = `RSV-${String(Math.floor(1000 + Math.random() * 9000))}`; const next = [...guestData, { name, code, type: guestForm.type, time: '—', state: 'Pending' as const }]; setGuestData(next); localStorage.setItem('rsvply-guests', JSON.stringify(next)); setGuestForm({ name: '', type: 'Regular' }); setUtilityView(null); setActiveView('Guests') }
  const metrics = { checked: guestData.filter(g => g.state === 'Checked in').length, pending: guestData.filter(g => g.state === 'Pending').length }

  return <div className="app">
    {menu && <button className="drawer-backdrop" aria-label="Close navigation" onClick={() => setMenu(false)} />}
    <aside id="event-navigation" className={menu ? 'sidebar open' : 'sidebar'} aria-hidden={!menu}>
      <div className="brand"><span className="brand-mark">R</span><span>rsvply</span></div><div className="event-switcher"><span className="eyebrow">ACTIVE EVENT</span><b>Ruang Rasa — Launch Night</b><span className="event-date">24 SEP 2026 <ChevronDown size={14}/></span></div>
      <nav>{navItems.map((item, i) => <button className={activeView === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => openView(item)}>{[<LayoutDashboard size={17}/>, <Users size={17}/>, <QrCode size={17}/>, <ScanLine size={17}/>][i]} {item}</button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => openUtility('Settings')}><Settings size={17}/> Settings</button><button className="nav-item" onClick={() => openUtility('Help centre')}><CircleHelp size={17}/> Help centre</button><button className="nav-item" onClick={() => { if (loggedIn) { localStorage.removeItem('rsvply-session'); setLoggedIn(false) } else openUtility('Login') }}><Users size={17}/> {loggedIn ? 'Logout' : 'Login'}</button><div className="profile"><span>RV</span><div><b>Rsvply admin</b><small>Event operations</small></div><button className="profile-menu-button" aria-label="Open profile menu" aria-expanded={profileMenu} onClick={() => setProfileMenu(!profileMenu)}><MoreHorizontal size={17}/></button>{profileMenu && <div className="profile-menu"><button onClick={() => openUtility('Settings')}>Account settings</button><button onClick={() => { setProfileMenu(false); if (loggedIn) { localStorage.removeItem('rsvply-session'); setLoggedIn(false) } else openUtility('Login') }}>{loggedIn ? 'Logout' : 'Login'}</button></div>}</div></div>
    </aside>
    <main><header><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation" aria-controls="event-navigation" aria-expanded={menu}><Menu size={20}/></button><div className="greeting"><span className="eyebrow">{activeView.toUpperCase()}</span><h1>Good morning, team.</h1></div><div className="header-actions"><button className="quiet" onClick={exportGuests} aria-label="Export guest data"><Download size={16}/> <span>Export</span></button><button className="primary" onClick={() => { setScanResult(null); setScanner(true) }}><ScanLine size={16}/> Open scanner</button></div></header>
      <div className="content">{activeView === 'Overview' && <Overview metrics={metrics} guestData={guestData} onScan={() => setScanner(true)} />}{activeView === 'Guests' && <GuestList guests={visible} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} onAdd={() => setUtilityView('Add guest')} />}{activeView === 'QR codes' && <QrList guests={guestData} images={qrImages} download={downloadQr} />}{activeView === 'Check-in' && <CheckInPage guests={guestData} onOpen={() => setScanner(true)} />}</div>
    </main>
    {utilityView && <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="utility-title"><div className="scanner-modal utility-modal"><button className="modal-close" onClick={() => setUtilityView(null)} aria-label="Close dialog"><X size={18}/></button><span className="eyebrow">{utilityView.toUpperCase()}</span><h2 id="utility-title">{utilityView === 'Login' ? 'Admin login' : utilityView}</h2>{utilityView === 'Add guest' && <><p className="muted">Tambah tamu. QR unik otomatis muncul di halaman QR codes.</p><label className="utility-row"><span>Name</span><input autoFocus value={guestForm.name} onChange={e => setGuestForm({ ...guestForm, name: e.target.value })} placeholder="Nama tamu" /></label><label className="utility-row"><span>Type</span><select value={guestForm.type} onChange={e => setGuestForm({ ...guestForm, type: e.target.value })}><option>Regular</option><option>VIP</option><option>Family</option></select></label><button className="primary scanner-close" onClick={addGuest}>Create guest + QR</button></>}{utilityView === 'Settings' && <><p className="muted">Pengaturan demo tersimpan lokal di browser ini.</p><label className="utility-row"><span>Event name</span><input value="Ruang Rasa — Launch Night" readOnly /></label><label className="utility-row"><span>Timezone</span><input value="WIB (UTC+7)" readOnly /></label></>}{utilityView === 'Help centre' && <><p className="muted">Alur cepat: buat tamu, buka QR codes, download QR, lalu petugas check-in lewat kode unik.</p><button className="quiet scanner-close" onClick={() => { setUtilityView(null); setActiveView('QR codes') }}>Open QR codes</button></>}{utilityView === 'Login' && <><p className="muted">Demo lokal. Belum terhubung backend. Isi email dan password apa pun untuk masuk.</p><label className="utility-row"><span>Email</span><input autoFocus type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} placeholder="admin@example.com" /></label><label className="utility-row"><span>Password</span><input type="password" value={loginPassword} onChange={e => setLoginPassword(e.target.value)} placeholder="••••••••" /></label><button className="primary scanner-close" disabled={!loginEmail || !loginPassword} onClick={() => { localStorage.setItem('rsvply-session', 'demo'); setLoggedIn(true); setUtilityView(null) }}>Login demo</button></>}</div></div>}
    {scanner && <div className="modal-layer" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><div className="scanner-modal"><button className="modal-close" onClick={() => setScanner(false)} aria-label="Close scanner"><X size={18}/></button><span className="eyebrow">CHECK-IN</span><h2 id="scanner-title">Scan guest QR</h2><p className="muted">Scan QR lewat kamera HP, atau masukkan kode manual.</p>{camera ? <div className="camera-box"><video ref={videoRef} playsInline muted /><button className="quiet scanner-close" onClick={() => setCamera(false)}>Stop camera</button></div> : <button className="primary scanner-close" onClick={() => { setScanResult(null); setCamera(true) }}>Use camera</button>}<label className="scan-input"><span className="eyebrow">GUEST CODE</span><input autoFocus value={scanCode} onChange={e => { setScanCode(e.target.value); setScanResult(null) }} onKeyDown={e => e.key === 'Enter' && checkIn()} placeholder="Contoh: RSV-0828" /></label><button className="primary scanner-close" onClick={checkIn}>Check-in guest</button>{scanResult && <p className={scanResult.includes('berhasil') ? 'scan-success' : 'scan-error'}>{scanResult}</p>}<button className="quiet scanner-close" onClick={() => setScanner(false)}>Close scanner</button></div></div>}
  </div>
}

function Overview({ metrics, guestData, onScan }: { metrics: { checked: number; pending: number }; guestData: Guest[]; onScan: () => void }) { const latest = guestData.find(g => g.state === 'Checked in'); return <><section className="intro"><div><p className="kicker">LIVE EVENT / DOORS OPEN</p><h2>Ruang Rasa<br/><em>Launch Night</em></h2><p className="muted">A quick read on tonight's arrivals. Last sync 2 minutes ago.</p></div><div className="intro-meta"><span><CalendarDays size={16}/> 24 September 2026</span><span><Clock3 size={16}/> 18:00 — 22:00 WIB</span></div></section><section className="metrics"><Metric label="Checked in" value={String(metrics.checked)} detail="of guest list" tone="olive"/><Metric label="Still expected" value={String(metrics.pending)} detail="waiting to arrive"/><Metric label="QR scans" value="341" detail="13 repeat scans"/><Metric label="Latest arrival" value={latest?.time || '—'} detail={latest?.name || 'No arrival'} tone="brown"/></section><GuestList guests={guestData} query="" setQuery={() => {}} filter="All guests" setFilter={() => {}} compact onScan={onScan} /></> }
function Metric({ label, value, detail, tone = '' }: { label: string; value: string; detail: string; tone?: string }) { return <article className={`metric ${tone}`}><p>{label}</p><strong>{value}</strong><span>{detail}</span></article> }
function GuestList({ guests, query, setQuery, filter, setFilter, compact = false, onScan, onAdd }: { guests: Guest[]; query: string; setQuery: (v: string) => void; filter: 'All guests' | 'Checked in' | 'Pending'; setFilter: (v: 'All guests' | 'Checked in' | 'Pending') => void; compact?: boolean; onScan?: () => void; onAdd?: () => void }) { return <section className="panel arrivals"><div className="panel-head"><div><span className="eyebrow">GUESTS</span><h3>{compact ? 'Recent check-ins' : 'Guest list'}</h3></div>{onScan ? <button className="text-button" onClick={onScan}>Scan guest <ScanLine size={15}/></button> : onAdd && <button className="primary" onClick={onAdd}>Add guest</button>}</div><div className="table-tools"><label><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search guests or code" /></label><select className="filter" value={filter} onChange={e => setFilter(e.target.value as typeof filter)} aria-label="Filter guests"><option>All guests</option><option>Checked in</option><option>Pending</option></select></div><div className="table"><div className="table-row table-label"><span>GUEST</span><span>TYPE</span><span>TIME</span><span>STATUS</span></div>{guests.map(g => <div className="table-row" key={g.code}><div className="guest"><span className="avatar">{g.name.split(' ').map(x => x[0]).join('')}</span><div><b>{g.name}</b><small>{g.code}</small></div></div><span className="type">{g.type}</span><span className="time">{g.time}</span><span className={`status ${g.state === 'Checked in' ? 'done' : 'pending'}`}>{g.state === 'Checked in' && <Check size={13}/>} {g.state}</span></div>)}</div></section> }
function QrList({ guests, images, download }: { guests: Guest[]; images: Record<string, string>; download: (g: Guest) => void }) { return <section className="panel arrivals"><div className="panel-head"><div><span className="eyebrow">QR CODES</span><h3>Guest passes</h3><p className="muted">Satu QR unik untuk satu tamu. Download lalu kirim atau print.</p></div></div><div className="qr-grid">{guests.map(g => <article className="qr-card" key={g.code}>{images[g.code] ? <img src={images[g.code]} alt={`QR ${g.name}`} /> : <div className="qr-loading">Generating</div>}<b>{g.name}</b><code>{g.code}</code><button className="text-button" onClick={() => download(g)} disabled={!images[g.code]}><Download size={14}/> Download PNG</button></article>)}</div></section> }
function CheckInPage({ guests, onOpen }: { guests: Guest[]; onOpen: () => void }) { return <section className="checkin-page"><div className="checkin-copy"><span className="eyebrow">DOOR DESK</span><h2>Ready to welcome<br/><em>your guests.</em></h2><p className="muted">Open scanner, enter the code printed on a guest pass, and the dashboard will reject repeat check-ins.</p><button className="primary" onClick={onOpen}><ScanLine size={17}/> Open scanner</button></div><div className="checkin-guide panel"><span className="eyebrow">CHECK-IN FLOW</span><div><b>01</b><span>Open scanner</span></div><div><b>02</b><span>Enter guest code</span></div><div><b>03</b><span>Confirm arrival</span></div><small>{guests.filter(g => g.state === 'Checked in').length} guests checked in so far</small></div></section> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
